### ISSUE TITLE
Script: Generate WMS YAML from object configs

### ISSUE THREAD

**Issue by ketilt** [KSSno/Klimakverna-Pilot1#32]
## Dependencies
- Depends on #30

## Specification
- Add optional field for WMS palettes into object configs
- [Palettes are defined here](https://docs.google.com/spreadsheets/d/1uBm2NZk4PBKHbwahuBnhcpQcpAzfSioNpUe7ETQ5hjA/edit?usp=sharing) but will be converted en masse to JSON format. Use example below to test
- Script should output one YAML file for all objects that have palettes defined

### YAML pattern
Described here: https://github.com/metno/mapgen-fastapi?tab=readme-ov-file#config-format

Many fields are static and can be reused from the example below, but these fields must be defined:
- pattern: filename of file
- base_netcdf_directory: lustre path of file
- styles
  - name: use variable name
  - colors, intervals, open_lowest_interval, open_highest_interval: from variable config

Example below:
```
  - pattern: '^.*(ensemble-mean_ssp370_both-bc-sn2018v2005_rawbc_norway_1km_diff-tas.nc)$'
    base_netcdf_directory: '/lustre/storeA/users/trygveas/Klima_i_Norge_2100/testdata_for_wms'
    module: 'mapgen.modules.generic_quicklook'
    module_function: 'generic_quicklook'
    mapfiles_path: '/mapfiles'
    styles:
      - name: 'Temperature'
        colors: ["#dd5f4d", "#b2182a", "#67001f", "#420114"]
        intervals: [0, 3, 4, 5, 10]
        open_lowest_interval: true
        open_highest_interval: true
```

## Suggestions
- Pattern can be a list of files, for example all scenario versions of one object

object config:
```
{
    "collection": "ClimateStatistics",
    "metadata": {
        "global": {...},
        "dataVariables": {...},
        "dataVariableNames": [...]
    }
    "palettes": {
        "colors": ["#D7B36A", "#E9D39D", "#EEE8C8", "#CEE9DF", "#A0DAD1", "#6EC0B5", "#3A9B92", "#147870", "#00594F", "#003C30"],
        "intervals" [-8, -4, 0, 4, 8, 12, 16, 20, 24],
        "openLowestInterval": TRUE
        "openHighestInterval": TRUE
    }
}
```
